name: Feature request / Предложение
description: Опишите задачу и ожидаемое поведение.
title: 'feat: '
labels:
- enhancement
body:
- type: textarea
  id: problem
  attributes:
    label: Какую задачу нужно решить? / Problem
  validations:
    required: true
- type: textarea
  id: behavior
  attributes:
    label: Желаемое поведение / Desired behavior
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Текущий обходной путь / Alternatives
  validations:
    required: false
- type: textarea
  id: examples
  attributes:
    label: Примеры / Examples
    description: Макет, скриншот или сценарий использования, если есть.
  validations:
    required: false
